---
title: 9、异常处理
icon: java
order: 9
date: 2022-06-22
category: 
    - java
tag: 
    - 基础语法
    - java
---
## 异常处理

### 1、异常概述和异常体系结构

异常的分类：error，exception
**编译时异常必须显示处理，运行时异常交给虚拟机。**

![image-20220710204105263](https://raw.githubusercontent.com/T4mako/ImageBed/main/image-20220710204105263.png)

```java
//Error
public class ErrorTest{
    public static void main(String[] args){
        //1、栈溢出：java.lang.StackOverflowError
        main(args);
        //2、堆溢出：java.lang.OutOfMemoryError
        Integer[] arr = new Integer[1024*1024*1024];
    }
}
```

![image-20220711141545219](https://raw.githubusercontent.com/T4mako/ImageBed/main/image-20220711141545219.png)

**蓝色：运行时异常**
**红色：编译时异常**

**编译时异常（checked）**
**运行时异常（unchecked）**

一、异常体系结构：
![image-20220711170136676](https://raw.githubusercontent.com/T4mako/ImageBed/main/image-20220711170136676.png)

常见异常：
```java
//运行时异常
public class ExceptionTest{
    
    //NullPointerException
    //空指针异常
    public void test1(){
        int[] arr = null;
        System.out.println(arr[1]);
        
        String str = null;
        System.out.println(str.charAt(0));
    }
    
    //ArrayIndexOutOfBoundsException
    //数组角标越界
    public void test2(){
        int[] arr = new int[2];
        System.out.println(arr[2]);
        
        String str = "abc";
        System.out.println(str.charAt(3));
    }
    
    //ClassCastExceotion
    //类型转换异常
    public void test3(){
        Object obj = new Date();
        String str = (String)abj;
    }
    
    //NumberFormateException
    //数据转换异常
    public void test4(){
        String str = "abc";
        int num = Integer.parseInt(str);
    }
    
    //InputMismatchException
    //输入不匹配
    public void test5(){
       Scanner scan = new Scanner(System.in);
       int score = scan.nextInt();//输入abc
    }
    
    //ArithmeticException
    //算数异常
    public void test6(){
        int a = 10;
        int b = 0;
        System.out.println(a/b);
    }
}
```

### 2、Java异常处理的方式

方式一：`try-catch-finally`
方式二：`throws+异常类型`

#### 异常的处理：抓抛模型

过程一：
“抛”：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常对象。并将此对象抛出。
一旦抛出对象后，其后的代码就不在执行

过程二：“抓”：
可以理解为异常的处理方式：①try-catch-finally ②throws

#### 1、try-catch-finally的使用

```java
try{
    //可能出现异常的代码
}catch(异常类型1 变量名1){
    //处理异常的方式1
}catch(异常类型2 变量名2){
    //处理异常的方式2
}catch(异常类型3 变量名3){
    //处理异常的方式3
}
......
finally{
    //一定会执行的代码
}
```

```java
public void test1{
    String str = "abc";
    try{
        int num = Integer.parseInt(str);//出现异常，直接进入catch
        System.out.println("1");
        
    }catch(NumberFormatException e){
        //String getMessage():
        System.out.println(e.getMessage());
        //printStakeTracce():
        e.printStakeTracce();
        System.out.println("出现数值转换异常");//处理掉异常，往下执行
    }
    System.out.println("2");
}
```

说明：
- finally是可选的
- 使用try将可能出现异常的代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，**去catch中匹配**
- 一旦try中异常对象匹配到某一个catch，进入catch中进行异常处理。**一旦处理完成，就跳出try-catch结构**（在没有写finally的情况）。==继续执行其后的代码==
- catch中异常类型注意子父类、先后顺序。父类声明在子类之上，报错。
- 常用的异常对象处理方式：①String getMessage()	②printStakeTracce()
- **在try结构中声明的变量，出了try结构后，就不能再被调用。**
- **try-catch-finally结构可以相互嵌套**

体会：
使用try-catch-finally处理编译时异常，将编译时异常转换为运行时异常，延迟出现。  
由于运行时异常比较常见，不针对运行时异常编写try-catch-finally。  
针对编译时异常，一定要考虑try-catch-finally

try-catch-finally中finally的使用
- finally是可选的
- finally中声明的是一定会被执行的代码。即使catch中又出现了异常，try中有return语句，catch中有return语句等情况
- 像数据库连接、输入输出流、网络编程Socket等资源，Jvm是不能自动回收的，我们需要手动进行资源的释放，此时资源释放就需要声明在finally中。

```java
public class FinallyTest{
    public void test1(){
        try{
            int a = 10;
        	int b = 0;
            System.out.println(a/b);
        }catch(ArithmeticExceptioin e){
            e.printStackTrace();
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            System.out.prinln("");
        }
	}
}
```

#### 2、throws+异常类型

1、`throws+异常类型`**写在方法的声明**处，指明此方法执行时，**可能会抛出的异常类型**。
一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。**异常代码后续的代码就不再执行。**
2、`try-catch-finally`：真正的将异常处理掉。  
`throws`只是将异常抛给了方法的调用者。并没有将异常处理掉

```java
public void ExceptionTest2{
    public void method1() throws FileNotFoundException,IOException{
        //异常
    }
    public void method2() throws IoException{
        method1();
    }
    }
}
```

方法重写的规则之一：
子类重写的方法抛出的异常不大于父类被重写的方法抛出的异常类型

#### 3、开发中try-catch-finally和throws的选择

- 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理。
- 执行的方法a中先后又调用了另外几个方法，这几个方法是递进关系执行的，建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑try-catch-finally方式进行胡成立

### 3、手动抛出异常对象

关于异常对象的产生：  
1. 系统自动生成的异常对象	
2. 手动生成并抛出一个异常对象（throw）
:::info
throws和throw的区别：
throw表示抛出一个异常的对象，生成异常对象的过程，声明在方法体内 throw new 异常类("abc")
throws属于异常处理的一种方式，声明在方法的声明处
:::

```java
public static void mian(String[] args){
    Student s = new Student();
    s.regist(-1001);//最后try-catch一下
    System.out.println(s);
}
class Student{
    private int id;
    public void regist(int id) throws Exception{
        if(id > 0){
            this.id = id;
        }else{
            //System.out.pringln("非法");
            //手动抛出异常
            //throw new RuntimeException("您输入的数据非法");
            throw new Exception("您输入的数据非法");
        }
	}
}
```

### 4、用户自定义异常类

自定义异常类：
- 继承于现有的异常结构：RuntimeException、Exception
- 提供全局变量：serialVersionUID
- 提供重载的构造器

```java
public class MyException extends RuntimeException{
    static final long serialVersionUID = -61641614198984L;
    public MyException(){
        
	}
    public MyException(String msg){
        super(msg);
    }
}
```
